### ISSUE TITLE
No developer tools scripts folder 

### ISSUE THREAD

**Issue by rajcrk** [fnplus/initDev#1]
Seems like the README is more updated than the actual codebase. I don't see a folder mentioning script files for developer tools, while I see one for OS and Roles.
It would be nice to lay the groundwork for creating developer tools script files in the future by creating a new directory for tools.

Would also be super awesome if we could start developer tools by adding in a script file for git (Ubuntu). since its where we all once started!.

FYI this looks like a pretty good first-timers issue.

**Comment by xlogix** [comment]
It seems like a nice idea! Thanks for taking a look at this project. I didn't find the time to add more resources. Although, I would happily accept any PRs you send here. And, I'll also add more things here.

**Comment by rajcrk** [comment]
@xlogix I believe that there are two ways by which we can structure out this.
1. Create separate script files for each tool that we need (git, docker, vim..), which will result in a cluster of script files for each tool. plus once we factor in the possibility of multiple OS it will even be more. (We will have a ton of people contributing in a small amount though).

2. Create two script files for developer-tools and developer-apps and include all the tools that we need into them.

Would love to get your view on them. Since this decision might shape the structure of this repo in a huge way in the future. I`m counting on your decision.

Thanks in advance!

**Comment by xlogix** [comment]
Hmm... What if we do both? We keep the separate script files doing what they're supposed to do but we also create a wrapper script that can call those individual scripts as needed. This would allow this project to be comparatively active too since lot of developers would be interested in contributing small.

I had this idea for creating a front-end for this project which could allow users to drag and drop what they need like [Scratch](https://scratch.mit.edu/) or Google's Blockly. We can then create the wrapper script based on the user's requirements and call those individual scripts. What do you think?

**Comment by rajcrk** [comment]
Hmm... I think we're onto something big here. This idea which you're saying is pretty useful and it would make the project a lot more awesome ( which is good :-) ). I believe this project would benefit a lot more people if we set the future roadmap to your idea. 

For now, I`ll work on creating individual scripts for tools and applications and well see from there!

**Comment by xlogix** [comment]
Alright! Cool
